// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PlayerDb.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_PlayerDb_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_PlayerDb_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3015000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3015006 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/map.h>  // IWYU pragma: export
#include <google/protobuf/map_entry.h>
#include <google/protobuf/map_field_inl.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_PlayerDb_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_PlayerDb_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[11]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_PlayerDb_2eproto;
::PROTOBUF_NAMESPACE_ID::Metadata descriptor_table_PlayerDb_2eproto_metadata_getter(int index);
class MsgHero;
struct MsgHeroDefaultTypeInternal;
extern MsgHeroDefaultTypeInternal _MsgHero_default_instance_;
class MsgHero_AttrsEntry_DoNotUse;
struct MsgHero_AttrsEntry_DoNotUseDefaultTypeInternal;
extern MsgHero_AttrsEntry_DoNotUseDefaultTypeInternal _MsgHero_AttrsEntry_DoNotUse_default_instance_;
class MsgHero_MsgPlayerBagItemEntry_DoNotUse;
struct MsgHero_MsgPlayerBagItemEntry_DoNotUseDefaultTypeInternal;
extern MsgHero_MsgPlayerBagItemEntry_DoNotUseDefaultTypeInternal _MsgHero_MsgPlayerBagItemEntry_DoNotUse_default_instance_;
class MsgPlayer;
struct MsgPlayerDefaultTypeInternal;
extern MsgPlayerDefaultTypeInternal _MsgPlayer_default_instance_;
class MsgPlayerBag;
struct MsgPlayerBagDefaultTypeInternal;
extern MsgPlayerBagDefaultTypeInternal _MsgPlayerBag_default_instance_;
class MsgPlayerBagItem;
struct MsgPlayerBagItemDefaultTypeInternal;
extern MsgPlayerBagItemDefaultTypeInternal _MsgPlayerBagItem_default_instance_;
class MsgPlayerBagItem_AttrEntry_DoNotUse;
struct MsgPlayerBagItem_AttrEntry_DoNotUseDefaultTypeInternal;
extern MsgPlayerBagItem_AttrEntry_DoNotUseDefaultTypeInternal _MsgPlayerBagItem_AttrEntry_DoNotUse_default_instance_;
class MsgPlayerBagItem_DynaAttrEntry_DoNotUse;
struct MsgPlayerBagItem_DynaAttrEntry_DoNotUseDefaultTypeInternal;
extern MsgPlayerBagItem_DynaAttrEntry_DoNotUseDefaultTypeInternal _MsgPlayerBagItem_DynaAttrEntry_DoNotUse_default_instance_;
class MsgPlayerBag_MsgPlayerBagItemEntry_DoNotUse;
struct MsgPlayerBag_MsgPlayerBagItemEntry_DoNotUseDefaultTypeInternal;
extern MsgPlayerBag_MsgPlayerBagItemEntry_DoNotUseDefaultTypeInternal _MsgPlayerBag_MsgPlayerBagItemEntry_DoNotUse_default_instance_;
class MsgPlayer_MsgHeroEntry_DoNotUse;
struct MsgPlayer_MsgHeroEntry_DoNotUseDefaultTypeInternal;
extern MsgPlayer_MsgHeroEntry_DoNotUseDefaultTypeInternal _MsgPlayer_MsgHeroEntry_DoNotUse_default_instance_;
class MsgPlayer_MsgPlayerBagEntry_DoNotUse;
struct MsgPlayer_MsgPlayerBagEntry_DoNotUseDefaultTypeInternal;
extern MsgPlayer_MsgPlayerBagEntry_DoNotUseDefaultTypeInternal _MsgPlayer_MsgPlayerBagEntry_DoNotUse_default_instance_;
PROTOBUF_NAMESPACE_OPEN
template<> ::MsgHero* Arena::CreateMaybeMessage<::MsgHero>(Arena*);
template<> ::MsgHero_AttrsEntry_DoNotUse* Arena::CreateMaybeMessage<::MsgHero_AttrsEntry_DoNotUse>(Arena*);
template<> ::MsgHero_MsgPlayerBagItemEntry_DoNotUse* Arena::CreateMaybeMessage<::MsgHero_MsgPlayerBagItemEntry_DoNotUse>(Arena*);
template<> ::MsgPlayer* Arena::CreateMaybeMessage<::MsgPlayer>(Arena*);
template<> ::MsgPlayerBag* Arena::CreateMaybeMessage<::MsgPlayerBag>(Arena*);
template<> ::MsgPlayerBagItem* Arena::CreateMaybeMessage<::MsgPlayerBagItem>(Arena*);
template<> ::MsgPlayerBagItem_AttrEntry_DoNotUse* Arena::CreateMaybeMessage<::MsgPlayerBagItem_AttrEntry_DoNotUse>(Arena*);
template<> ::MsgPlayerBagItem_DynaAttrEntry_DoNotUse* Arena::CreateMaybeMessage<::MsgPlayerBagItem_DynaAttrEntry_DoNotUse>(Arena*);
template<> ::MsgPlayerBag_MsgPlayerBagItemEntry_DoNotUse* Arena::CreateMaybeMessage<::MsgPlayerBag_MsgPlayerBagItemEntry_DoNotUse>(Arena*);
template<> ::MsgPlayer_MsgHeroEntry_DoNotUse* Arena::CreateMaybeMessage<::MsgPlayer_MsgHeroEntry_DoNotUse>(Arena*);
template<> ::MsgPlayer_MsgPlayerBagEntry_DoNotUse* Arena::CreateMaybeMessage<::MsgPlayer_MsgPlayerBagEntry_DoNotUse>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

// ===================================================================

class MsgPlayerBagItem_AttrEntry_DoNotUse : public ::PROTOBUF_NAMESPACE_ID::internal::MapEntry<MsgPlayerBagItem_AttrEntry_DoNotUse, 
    ::PROTOBUF_NAMESPACE_ID::int32, ::PROTOBUF_NAMESPACE_ID::int32,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_INT32,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_INT32> {
public:
  typedef ::PROTOBUF_NAMESPACE_ID::internal::MapEntry<MsgPlayerBagItem_AttrEntry_DoNotUse, 
    ::PROTOBUF_NAMESPACE_ID::int32, ::PROTOBUF_NAMESPACE_ID::int32,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_INT32,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_INT32> SuperType;
  MsgPlayerBagItem_AttrEntry_DoNotUse();
  explicit constexpr MsgPlayerBagItem_AttrEntry_DoNotUse(
      ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);
  explicit MsgPlayerBagItem_AttrEntry_DoNotUse(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  void MergeFrom(const MsgPlayerBagItem_AttrEntry_DoNotUse& other);
  static const MsgPlayerBagItem_AttrEntry_DoNotUse* internal_default_instance() { return reinterpret_cast<const MsgPlayerBagItem_AttrEntry_DoNotUse*>(&_MsgPlayerBagItem_AttrEntry_DoNotUse_default_instance_); }
  static bool ValidateKey(void*) { return true; }
  static bool ValidateValue(void*) { return true; }
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& other) final;
  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_PlayerDb_2eproto);
    return ::descriptor_table_PlayerDb_2eproto.file_level_metadata[0];
  }

  public:
};

// -------------------------------------------------------------------

class MsgPlayerBagItem_DynaAttrEntry_DoNotUse : public ::PROTOBUF_NAMESPACE_ID::internal::MapEntry<MsgPlayerBagItem_DynaAttrEntry_DoNotUse, 
    ::PROTOBUF_NAMESPACE_ID::int32, ::PROTOBUF_NAMESPACE_ID::int32,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_INT32,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_INT32> {
public:
  typedef ::PROTOBUF_NAMESPACE_ID::internal::MapEntry<MsgPlayerBagItem_DynaAttrEntry_DoNotUse, 
    ::PROTOBUF_NAMESPACE_ID::int32, ::PROTOBUF_NAMESPACE_ID::int32,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_INT32,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_INT32> SuperType;
  MsgPlayerBagItem_DynaAttrEntry_DoNotUse();
  explicit constexpr MsgPlayerBagItem_DynaAttrEntry_DoNotUse(
      ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);
  explicit MsgPlayerBagItem_DynaAttrEntry_DoNotUse(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  void MergeFrom(const MsgPlayerBagItem_DynaAttrEntry_DoNotUse& other);
  static const MsgPlayerBagItem_DynaAttrEntry_DoNotUse* internal_default_instance() { return reinterpret_cast<const MsgPlayerBagItem_DynaAttrEntry_DoNotUse*>(&_MsgPlayerBagItem_DynaAttrEntry_DoNotUse_default_instance_); }
  static bool ValidateKey(void*) { return true; }
  static bool ValidateValue(void*) { return true; }
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& other) final;
  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_PlayerDb_2eproto);
    return ::descriptor_table_PlayerDb_2eproto.file_level_metadata[1];
  }

  public:
};

// -------------------------------------------------------------------

class MsgPlayerBagItem PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:MsgPlayerBagItem) */ {
 public:
  inline MsgPlayerBagItem() : MsgPlayerBagItem(nullptr) {}
  virtual ~MsgPlayerBagItem();
  explicit constexpr MsgPlayerBagItem(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  MsgPlayerBagItem(const MsgPlayerBagItem& from);
  MsgPlayerBagItem(MsgPlayerBagItem&& from) noexcept
    : MsgPlayerBagItem() {
    *this = ::std::move(from);
  }

  inline MsgPlayerBagItem& operator=(const MsgPlayerBagItem& from) {
    CopyFrom(from);
    return *this;
  }
  inline MsgPlayerBagItem& operator=(MsgPlayerBagItem&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const MsgPlayerBagItem& default_instance() {
    return *internal_default_instance();
  }
  static inline const MsgPlayerBagItem* internal_default_instance() {
    return reinterpret_cast<const MsgPlayerBagItem*>(
               &_MsgPlayerBagItem_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(MsgPlayerBagItem& a, MsgPlayerBagItem& b) {
    a.Swap(&b);
  }
  inline void Swap(MsgPlayerBagItem* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(MsgPlayerBagItem* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline MsgPlayerBagItem* New() const final {
    return CreateMaybeMessage<MsgPlayerBagItem>(nullptr);
  }

  MsgPlayerBagItem* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<MsgPlayerBagItem>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const MsgPlayerBagItem& from);
  void MergeFrom(const MsgPlayerBagItem& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(MsgPlayerBagItem* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "MsgPlayerBagItem";
  }
  protected:
  explicit MsgPlayerBagItem(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    return ::descriptor_table_PlayerDb_2eproto_metadata_getter(kIndexInFileMessages);
  }

  public:

  // nested types ----------------------------------------------------


  // accessors -------------------------------------------------------

  enum : int {
    kAttrFieldNumber = 4,
    kDynaAttrFieldNumber = 5,
    kSkillsFieldNumber = 6,
    kUidFieldNumber = 1,
    kIdFieldNumber = 2,
    kCntFieldNumber = 3,
  };
  // map<int32, int32> attr = 4;
  int attr_size() const;
  private:
  int _internal_attr_size() const;
  public:
  void clear_attr();
  private:
  const ::PROTOBUF_NAMESPACE_ID::Map< ::PROTOBUF_NAMESPACE_ID::int32, ::PROTOBUF_NAMESPACE_ID::int32 >&
      _internal_attr() const;
  ::PROTOBUF_NAMESPACE_ID::Map< ::PROTOBUF_NAMESPACE_ID::int32, ::PROTOBUF_NAMESPACE_ID::int32 >*
      _internal_mutable_attr();
  public:
  const ::PROTOBUF_NAMESPACE_ID::Map< ::PROTOBUF_NAMESPACE_ID::int32, ::PROTOBUF_NAMESPACE_ID::int32 >&
      attr() const;
  ::PROTOBUF_NAMESPACE_ID::Map< ::PROTOBUF_NAMESPACE_ID::int32, ::PROTOBUF_NAMESPACE_ID::int32 >*
      mutable_attr();

  // map<int32, int32> dynaAttr = 5;
  int dynaattr_size() const;
  private:
  int _internal_dynaattr_size() const;
  public:
  void clear_dynaattr();
  private:
  const ::PROTOBUF_NAMESPACE_ID::Map< ::PROTOBUF_NAMESPACE_ID::int32, ::PROTOBUF_NAMESPACE_ID::int32 >&
      _internal_dynaattr() const;
  ::PROTOBUF_NAMESPACE_ID::Map< ::PROTOBUF_NAMESPACE_ID::int32, ::PROTOBUF_NAMESPACE_ID::int32 >*
      _internal_mutable_dynaattr();
  public:
  const ::PROTOBUF_NAMESPACE_ID::Map< ::PROTOBUF_NAMESPACE_ID::int32, ::PROTOBUF_NAMESPACE_ID::int32 >&
      dynaattr() const;
  ::PROTOBUF_NAMESPACE_ID::Map< ::PROTOBUF_NAMESPACE_ID::int32, ::PROTOBUF_NAMESPACE_ID::int32 >*
      mutable_dynaattr();

  // repeated int32 skills = 6;
  int skills_size() const;
  private:
  int _internal_skills_size() const;
  public:
  void clear_skills();
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_skills(int index) const;
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int32 >&
      _internal_skills() const;
  void _internal_add_skills(::PROTOBUF_NAMESPACE_ID::int32 value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int32 >*
      _internal_mutable_skills();
  public:
  ::PROTOBUF_NAMESPACE_ID::int32 skills(int index) const;
  void set_skills(int index, ::PROTOBUF_NAMESPACE_ID::int32 value);
  void add_skills(::PROTOBUF_NAMESPACE_ID::int32 value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int32 >&
      skills() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int32 >*
      mutable_skills();

  // int32 uid = 1;
  void clear_uid();
  ::PROTOBUF_NAMESPACE_ID::int32 uid() const;
  void set_uid(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_uid() const;
  void _internal_set_uid(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // int32 id = 2;
  void clear_id();
  ::PROTOBUF_NAMESPACE_ID::int32 id() const;
  void set_id(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_id() const;
  void _internal_set_id(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // int64 cnt = 3;
  void clear_cnt();
  ::PROTOBUF_NAMESPACE_ID::int64 cnt() const;
  void set_cnt(::PROTOBUF_NAMESPACE_ID::int64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int64 _internal_cnt() const;
  void _internal_set_cnt(::PROTOBUF_NAMESPACE_ID::int64 value);
  public:

  // @@protoc_insertion_point(class_scope:MsgPlayerBagItem)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::MapField<
      MsgPlayerBagItem_AttrEntry_DoNotUse,
      ::PROTOBUF_NAMESPACE_ID::int32, ::PROTOBUF_NAMESPACE_ID::int32,
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_INT32,
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_INT32> attr_;
  ::PROTOBUF_NAMESPACE_ID::internal::MapField<
      MsgPlayerBagItem_DynaAttrEntry_DoNotUse,
      ::PROTOBUF_NAMESPACE_ID::int32, ::PROTOBUF_NAMESPACE_ID::int32,
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_INT32,
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_INT32> dynaattr_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int32 > skills_;
  mutable std::atomic<int> _skills_cached_byte_size_;
  ::PROTOBUF_NAMESPACE_ID::int32 uid_;
  ::PROTOBUF_NAMESPACE_ID::int32 id_;
  ::PROTOBUF_NAMESPACE_ID::int64 cnt_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_PlayerDb_2eproto;
};
// -------------------------------------------------------------------

class MsgPlayerBag_MsgPlayerBagItemEntry_DoNotUse : public ::PROTOBUF_NAMESPACE_ID::internal::MapEntry<MsgPlayerBag_MsgPlayerBagItemEntry_DoNotUse, 
    ::PROTOBUF_NAMESPACE_ID::int32, ::MsgPlayerBagItem,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_INT32,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_MESSAGE> {
public:
  typedef ::PROTOBUF_NAMESPACE_ID::internal::MapEntry<MsgPlayerBag_MsgPlayerBagItemEntry_DoNotUse, 
    ::PROTOBUF_NAMESPACE_ID::int32, ::MsgPlayerBagItem,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_INT32,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_MESSAGE> SuperType;
  MsgPlayerBag_MsgPlayerBagItemEntry_DoNotUse();
  explicit constexpr MsgPlayerBag_MsgPlayerBagItemEntry_DoNotUse(
      ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);
  explicit MsgPlayerBag_MsgPlayerBagItemEntry_DoNotUse(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  void MergeFrom(const MsgPlayerBag_MsgPlayerBagItemEntry_DoNotUse& other);
  static const MsgPlayerBag_MsgPlayerBagItemEntry_DoNotUse* internal_default_instance() { return reinterpret_cast<const MsgPlayerBag_MsgPlayerBagItemEntry_DoNotUse*>(&_MsgPlayerBag_MsgPlayerBagItemEntry_DoNotUse_default_instance_); }
  static bool ValidateKey(void*) { return true; }
  static bool ValidateValue(void*) { return true; }
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& other) final;
  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_PlayerDb_2eproto);
    return ::descriptor_table_PlayerDb_2eproto.file_level_metadata[3];
  }

  public:
};

// -------------------------------------------------------------------

class MsgPlayerBag PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:MsgPlayerBag) */ {
 public:
  inline MsgPlayerBag() : MsgPlayerBag(nullptr) {}
  virtual ~MsgPlayerBag();
  explicit constexpr MsgPlayerBag(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  MsgPlayerBag(const MsgPlayerBag& from);
  MsgPlayerBag(MsgPlayerBag&& from) noexcept
    : MsgPlayerBag() {
    *this = ::std::move(from);
  }

  inline MsgPlayerBag& operator=(const MsgPlayerBag& from) {
    CopyFrom(from);
    return *this;
  }
  inline MsgPlayerBag& operator=(MsgPlayerBag&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const MsgPlayerBag& default_instance() {
    return *internal_default_instance();
  }
  static inline const MsgPlayerBag* internal_default_instance() {
    return reinterpret_cast<const MsgPlayerBag*>(
               &_MsgPlayerBag_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(MsgPlayerBag& a, MsgPlayerBag& b) {
    a.Swap(&b);
  }
  inline void Swap(MsgPlayerBag* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(MsgPlayerBag* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline MsgPlayerBag* New() const final {
    return CreateMaybeMessage<MsgPlayerBag>(nullptr);
  }

  MsgPlayerBag* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<MsgPlayerBag>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const MsgPlayerBag& from);
  void MergeFrom(const MsgPlayerBag& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(MsgPlayerBag* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "MsgPlayerBag";
  }
  protected:
  explicit MsgPlayerBag(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    return ::descriptor_table_PlayerDb_2eproto_metadata_getter(kIndexInFileMessages);
  }

  public:

  // nested types ----------------------------------------------------


  // accessors -------------------------------------------------------

  enum : int {
    kMsgPlayerBagItemFieldNumber = 2,
    kCapFieldNumber = 1,
  };
  // map<int32, .MsgPlayerBagItem> msgPlayerBagItem = 2;
  int msgplayerbagitem_size() const;
  private:
  int _internal_msgplayerbagitem_size() const;
  public:
  void clear_msgplayerbagitem();
  private:
  const ::PROTOBUF_NAMESPACE_ID::Map< ::PROTOBUF_NAMESPACE_ID::int32, ::MsgPlayerBagItem >&
      _internal_msgplayerbagitem() const;
  ::PROTOBUF_NAMESPACE_ID::Map< ::PROTOBUF_NAMESPACE_ID::int32, ::MsgPlayerBagItem >*
      _internal_mutable_msgplayerbagitem();
  public:
  const ::PROTOBUF_NAMESPACE_ID::Map< ::PROTOBUF_NAMESPACE_ID::int32, ::MsgPlayerBagItem >&
      msgplayerbagitem() const;
  ::PROTOBUF_NAMESPACE_ID::Map< ::PROTOBUF_NAMESPACE_ID::int32, ::MsgPlayerBagItem >*
      mutable_msgplayerbagitem();

  // int32 cap = 1;
  void clear_cap();
  ::PROTOBUF_NAMESPACE_ID::int32 cap() const;
  void set_cap(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_cap() const;
  void _internal_set_cap(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // @@protoc_insertion_point(class_scope:MsgPlayerBag)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::MapField<
      MsgPlayerBag_MsgPlayerBagItemEntry_DoNotUse,
      ::PROTOBUF_NAMESPACE_ID::int32, ::MsgPlayerBagItem,
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_INT32,
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_MESSAGE> msgplayerbagitem_;
  ::PROTOBUF_NAMESPACE_ID::int32 cap_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_PlayerDb_2eproto;
};
// -------------------------------------------------------------------

class MsgHero_MsgPlayerBagItemEntry_DoNotUse : public ::PROTOBUF_NAMESPACE_ID::internal::MapEntry<MsgHero_MsgPlayerBagItemEntry_DoNotUse, 
    ::PROTOBUF_NAMESPACE_ID::int32, ::MsgPlayerBagItem,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_INT32,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_MESSAGE> {
public:
  typedef ::PROTOBUF_NAMESPACE_ID::internal::MapEntry<MsgHero_MsgPlayerBagItemEntry_DoNotUse, 
    ::PROTOBUF_NAMESPACE_ID::int32, ::MsgPlayerBagItem,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_INT32,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_MESSAGE> SuperType;
  MsgHero_MsgPlayerBagItemEntry_DoNotUse();
  explicit constexpr MsgHero_MsgPlayerBagItemEntry_DoNotUse(
      ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);
  explicit MsgHero_MsgPlayerBagItemEntry_DoNotUse(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  void MergeFrom(const MsgHero_MsgPlayerBagItemEntry_DoNotUse& other);
  static const MsgHero_MsgPlayerBagItemEntry_DoNotUse* internal_default_instance() { return reinterpret_cast<const MsgHero_MsgPlayerBagItemEntry_DoNotUse*>(&_MsgHero_MsgPlayerBagItemEntry_DoNotUse_default_instance_); }
  static bool ValidateKey(void*) { return true; }
  static bool ValidateValue(void*) { return true; }
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& other) final;
  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_PlayerDb_2eproto);
    return ::descriptor_table_PlayerDb_2eproto.file_level_metadata[5];
  }

  public:
};

// -------------------------------------------------------------------

class MsgHero_AttrsEntry_DoNotUse : public ::PROTOBUF_NAMESPACE_ID::internal::MapEntry<MsgHero_AttrsEntry_DoNotUse, 
    ::PROTOBUF_NAMESPACE_ID::int32, ::PROTOBUF_NAMESPACE_ID::int32,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_INT32,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_INT32> {
public:
  typedef ::PROTOBUF_NAMESPACE_ID::internal::MapEntry<MsgHero_AttrsEntry_DoNotUse, 
    ::PROTOBUF_NAMESPACE_ID::int32, ::PROTOBUF_NAMESPACE_ID::int32,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_INT32,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_INT32> SuperType;
  MsgHero_AttrsEntry_DoNotUse();
  explicit constexpr MsgHero_AttrsEntry_DoNotUse(
      ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);
  explicit MsgHero_AttrsEntry_DoNotUse(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  void MergeFrom(const MsgHero_AttrsEntry_DoNotUse& other);
  static const MsgHero_AttrsEntry_DoNotUse* internal_default_instance() { return reinterpret_cast<const MsgHero_AttrsEntry_DoNotUse*>(&_MsgHero_AttrsEntry_DoNotUse_default_instance_); }
  static bool ValidateKey(void*) { return true; }
  static bool ValidateValue(void*) { return true; }
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& other) final;
  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_PlayerDb_2eproto);
    return ::descriptor_table_PlayerDb_2eproto.file_level_metadata[6];
  }

  public:
};

// -------------------------------------------------------------------

class MsgHero PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:MsgHero) */ {
 public:
  inline MsgHero() : MsgHero(nullptr) {}
  virtual ~MsgHero();
  explicit constexpr MsgHero(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  MsgHero(const MsgHero& from);
  MsgHero(MsgHero&& from) noexcept
    : MsgHero() {
    *this = ::std::move(from);
  }

  inline MsgHero& operator=(const MsgHero& from) {
    CopyFrom(from);
    return *this;
  }
  inline MsgHero& operator=(MsgHero&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const MsgHero& default_instance() {
    return *internal_default_instance();
  }
  static inline const MsgHero* internal_default_instance() {
    return reinterpret_cast<const MsgHero*>(
               &_MsgHero_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    7;

  friend void swap(MsgHero& a, MsgHero& b) {
    a.Swap(&b);
  }
  inline void Swap(MsgHero* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(MsgHero* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline MsgHero* New() const final {
    return CreateMaybeMessage<MsgHero>(nullptr);
  }

  MsgHero* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<MsgHero>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const MsgHero& from);
  void MergeFrom(const MsgHero& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(MsgHero* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "MsgHero";
  }
  protected:
  explicit MsgHero(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    return ::descriptor_table_PlayerDb_2eproto_metadata_getter(kIndexInFileMessages);
  }

  public:

  // nested types ----------------------------------------------------


  // accessors -------------------------------------------------------

  enum : int {
    kMsgPlayerBagItemFieldNumber = 4,
    kAttrsFieldNumber = 5,
    kUidFieldNumber = 1,
    kIdFieldNumber = 2,
    kLvFieldNumber = 3,
  };
  // map<int32, .MsgPlayerBagItem> msgPlayerBagItem = 4;
  int msgplayerbagitem_size() const;
  private:
  int _internal_msgplayerbagitem_size() const;
  public:
  void clear_msgplayerbagitem();
  private:
  const ::PROTOBUF_NAMESPACE_ID::Map< ::PROTOBUF_NAMESPACE_ID::int32, ::MsgPlayerBagItem >&
      _internal_msgplayerbagitem() const;
  ::PROTOBUF_NAMESPACE_ID::Map< ::PROTOBUF_NAMESPACE_ID::int32, ::MsgPlayerBagItem >*
      _internal_mutable_msgplayerbagitem();
  public:
  const ::PROTOBUF_NAMESPACE_ID::Map< ::PROTOBUF_NAMESPACE_ID::int32, ::MsgPlayerBagItem >&
      msgplayerbagitem() const;
  ::PROTOBUF_NAMESPACE_ID::Map< ::PROTOBUF_NAMESPACE_ID::int32, ::MsgPlayerBagItem >*
      mutable_msgplayerbagitem();

  // map<int32, int32> attrs = 5;
  int attrs_size() const;
  private:
  int _internal_attrs_size() const;
  public:
  void clear_attrs();
  private:
  const ::PROTOBUF_NAMESPACE_ID::Map< ::PROTOBUF_NAMESPACE_ID::int32, ::PROTOBUF_NAMESPACE_ID::int32 >&
      _internal_attrs() const;
  ::PROTOBUF_NAMESPACE_ID::Map< ::PROTOBUF_NAMESPACE_ID::int32, ::PROTOBUF_NAMESPACE_ID::int32 >*
      _internal_mutable_attrs();
  public:
  const ::PROTOBUF_NAMESPACE_ID::Map< ::PROTOBUF_NAMESPACE_ID::int32, ::PROTOBUF_NAMESPACE_ID::int32 >&
      attrs() const;
  ::PROTOBUF_NAMESPACE_ID::Map< ::PROTOBUF_NAMESPACE_ID::int32, ::PROTOBUF_NAMESPACE_ID::int32 >*
      mutable_attrs();

  // int32 uid = 1;
  void clear_uid();
  ::PROTOBUF_NAMESPACE_ID::int32 uid() const;
  void set_uid(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_uid() const;
  void _internal_set_uid(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // int32 id = 2;
  void clear_id();
  ::PROTOBUF_NAMESPACE_ID::int32 id() const;
  void set_id(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_id() const;
  void _internal_set_id(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // int32 lv = 3;
  void clear_lv();
  ::PROTOBUF_NAMESPACE_ID::int32 lv() const;
  void set_lv(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_lv() const;
  void _internal_set_lv(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // @@protoc_insertion_point(class_scope:MsgHero)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::MapField<
      MsgHero_MsgPlayerBagItemEntry_DoNotUse,
      ::PROTOBUF_NAMESPACE_ID::int32, ::MsgPlayerBagItem,
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_INT32,
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_MESSAGE> msgplayerbagitem_;
  ::PROTOBUF_NAMESPACE_ID::internal::MapField<
      MsgHero_AttrsEntry_DoNotUse,
      ::PROTOBUF_NAMESPACE_ID::int32, ::PROTOBUF_NAMESPACE_ID::int32,
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_INT32,
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_INT32> attrs_;
  ::PROTOBUF_NAMESPACE_ID::int32 uid_;
  ::PROTOBUF_NAMESPACE_ID::int32 id_;
  ::PROTOBUF_NAMESPACE_ID::int32 lv_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_PlayerDb_2eproto;
};
// -------------------------------------------------------------------

class MsgPlayer_MsgPlayerBagEntry_DoNotUse : public ::PROTOBUF_NAMESPACE_ID::internal::MapEntry<MsgPlayer_MsgPlayerBagEntry_DoNotUse, 
    ::PROTOBUF_NAMESPACE_ID::int32, ::MsgPlayerBag,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_INT32,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_MESSAGE> {
public:
  typedef ::PROTOBUF_NAMESPACE_ID::internal::MapEntry<MsgPlayer_MsgPlayerBagEntry_DoNotUse, 
    ::PROTOBUF_NAMESPACE_ID::int32, ::MsgPlayerBag,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_INT32,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_MESSAGE> SuperType;
  MsgPlayer_MsgPlayerBagEntry_DoNotUse();
  explicit constexpr MsgPlayer_MsgPlayerBagEntry_DoNotUse(
      ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);
  explicit MsgPlayer_MsgPlayerBagEntry_DoNotUse(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  void MergeFrom(const MsgPlayer_MsgPlayerBagEntry_DoNotUse& other);
  static const MsgPlayer_MsgPlayerBagEntry_DoNotUse* internal_default_instance() { return reinterpret_cast<const MsgPlayer_MsgPlayerBagEntry_DoNotUse*>(&_MsgPlayer_MsgPlayerBagEntry_DoNotUse_default_instance_); }
  static bool ValidateKey(void*) { return true; }
  static bool ValidateValue(void*) { return true; }
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& other) final;
  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_PlayerDb_2eproto);
    return ::descriptor_table_PlayerDb_2eproto.file_level_metadata[8];
  }

  public:
};

// -------------------------------------------------------------------

class MsgPlayer_MsgHeroEntry_DoNotUse : public ::PROTOBUF_NAMESPACE_ID::internal::MapEntry<MsgPlayer_MsgHeroEntry_DoNotUse, 
    ::PROTOBUF_NAMESPACE_ID::int32, ::MsgHero,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_INT32,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_MESSAGE> {
public:
  typedef ::PROTOBUF_NAMESPACE_ID::internal::MapEntry<MsgPlayer_MsgHeroEntry_DoNotUse, 
    ::PROTOBUF_NAMESPACE_ID::int32, ::MsgHero,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_INT32,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_MESSAGE> SuperType;
  MsgPlayer_MsgHeroEntry_DoNotUse();
  explicit constexpr MsgPlayer_MsgHeroEntry_DoNotUse(
      ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);
  explicit MsgPlayer_MsgHeroEntry_DoNotUse(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  void MergeFrom(const MsgPlayer_MsgHeroEntry_DoNotUse& other);
  static const MsgPlayer_MsgHeroEntry_DoNotUse* internal_default_instance() { return reinterpret_cast<const MsgPlayer_MsgHeroEntry_DoNotUse*>(&_MsgPlayer_MsgHeroEntry_DoNotUse_default_instance_); }
  static bool ValidateKey(void*) { return true; }
  static bool ValidateValue(void*) { return true; }
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& other) final;
  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_PlayerDb_2eproto);
    return ::descriptor_table_PlayerDb_2eproto.file_level_metadata[9];
  }

  public:
};

// -------------------------------------------------------------------

class MsgPlayer PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:MsgPlayer) */ {
 public:
  inline MsgPlayer() : MsgPlayer(nullptr) {}
  virtual ~MsgPlayer();
  explicit constexpr MsgPlayer(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  MsgPlayer(const MsgPlayer& from);
  MsgPlayer(MsgPlayer&& from) noexcept
    : MsgPlayer() {
    *this = ::std::move(from);
  }

  inline MsgPlayer& operator=(const MsgPlayer& from) {
    CopyFrom(from);
    return *this;
  }
  inline MsgPlayer& operator=(MsgPlayer&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const MsgPlayer& default_instance() {
    return *internal_default_instance();
  }
  static inline const MsgPlayer* internal_default_instance() {
    return reinterpret_cast<const MsgPlayer*>(
               &_MsgPlayer_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    10;

  friend void swap(MsgPlayer& a, MsgPlayer& b) {
    a.Swap(&b);
  }
  inline void Swap(MsgPlayer* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(MsgPlayer* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline MsgPlayer* New() const final {
    return CreateMaybeMessage<MsgPlayer>(nullptr);
  }

  MsgPlayer* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<MsgPlayer>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const MsgPlayer& from);
  void MergeFrom(const MsgPlayer& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(MsgPlayer* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "MsgPlayer";
  }
  protected:
  explicit MsgPlayer(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    return ::descriptor_table_PlayerDb_2eproto_metadata_getter(kIndexInFileMessages);
  }

  public:

  // nested types ----------------------------------------------------


  // accessors -------------------------------------------------------

  enum : int {
    kMsgPlayerBagFieldNumber = 3,
    kMsgHeroFieldNumber = 4,
    kNameFieldNumber = 2,
    kUidFieldNumber = 1,
  };
  // map<int32, .MsgPlayerBag> msgPlayerBag = 3;
  int msgplayerbag_size() const;
  private:
  int _internal_msgplayerbag_size() const;
  public:
  void clear_msgplayerbag();
  private:
  const ::PROTOBUF_NAMESPACE_ID::Map< ::PROTOBUF_NAMESPACE_ID::int32, ::MsgPlayerBag >&
      _internal_msgplayerbag() const;
  ::PROTOBUF_NAMESPACE_ID::Map< ::PROTOBUF_NAMESPACE_ID::int32, ::MsgPlayerBag >*
      _internal_mutable_msgplayerbag();
  public:
  const ::PROTOBUF_NAMESPACE_ID::Map< ::PROTOBUF_NAMESPACE_ID::int32, ::MsgPlayerBag >&
      msgplayerbag() const;
  ::PROTOBUF_NAMESPACE_ID::Map< ::PROTOBUF_NAMESPACE_ID::int32, ::MsgPlayerBag >*
      mutable_msgplayerbag();

  // map<int32, .MsgHero> msgHero = 4;
  int msghero_size() const;
  private:
  int _internal_msghero_size() const;
  public:
  void clear_msghero();
  private:
  const ::PROTOBUF_NAMESPACE_ID::Map< ::PROTOBUF_NAMESPACE_ID::int32, ::MsgHero >&
      _internal_msghero() const;
  ::PROTOBUF_NAMESPACE_ID::Map< ::PROTOBUF_NAMESPACE_ID::int32, ::MsgHero >*
      _internal_mutable_msghero();
  public:
  const ::PROTOBUF_NAMESPACE_ID::Map< ::PROTOBUF_NAMESPACE_ID::int32, ::MsgHero >&
      msghero() const;
  ::PROTOBUF_NAMESPACE_ID::Map< ::PROTOBUF_NAMESPACE_ID::int32, ::MsgHero >*
      mutable_msghero();

  // string name = 2;
  void clear_name();
  const std::string& name() const;
  void set_name(const std::string& value);
  void set_name(std::string&& value);
  void set_name(const char* value);
  void set_name(const char* value, size_t size);
  std::string* mutable_name();
  std::string* release_name();
  void set_allocated_name(std::string* name);
  private:
  const std::string& _internal_name() const;
  void _internal_set_name(const std::string& value);
  std::string* _internal_mutable_name();
  public:

  // int32 uid = 1;
  void clear_uid();
  ::PROTOBUF_NAMESPACE_ID::int32 uid() const;
  void set_uid(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_uid() const;
  void _internal_set_uid(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // @@protoc_insertion_point(class_scope:MsgPlayer)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::MapField<
      MsgPlayer_MsgPlayerBagEntry_DoNotUse,
      ::PROTOBUF_NAMESPACE_ID::int32, ::MsgPlayerBag,
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_INT32,
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_MESSAGE> msgplayerbag_;
  ::PROTOBUF_NAMESPACE_ID::internal::MapField<
      MsgPlayer_MsgHeroEntry_DoNotUse,
      ::PROTOBUF_NAMESPACE_ID::int32, ::MsgHero,
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_INT32,
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_MESSAGE> msghero_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr name_;
  ::PROTOBUF_NAMESPACE_ID::int32 uid_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_PlayerDb_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// MsgPlayerBagItem

// int32 uid = 1;
inline void MsgPlayerBagItem::clear_uid() {
  uid_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 MsgPlayerBagItem::_internal_uid() const {
  return uid_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 MsgPlayerBagItem::uid() const {
  // @@protoc_insertion_point(field_get:MsgPlayerBagItem.uid)
  return _internal_uid();
}
inline void MsgPlayerBagItem::_internal_set_uid(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  uid_ = value;
}
inline void MsgPlayerBagItem::set_uid(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_uid(value);
  // @@protoc_insertion_point(field_set:MsgPlayerBagItem.uid)
}

// int32 id = 2;
inline void MsgPlayerBagItem::clear_id() {
  id_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 MsgPlayerBagItem::_internal_id() const {
  return id_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 MsgPlayerBagItem::id() const {
  // @@protoc_insertion_point(field_get:MsgPlayerBagItem.id)
  return _internal_id();
}
inline void MsgPlayerBagItem::_internal_set_id(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  id_ = value;
}
inline void MsgPlayerBagItem::set_id(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_id(value);
  // @@protoc_insertion_point(field_set:MsgPlayerBagItem.id)
}

// int64 cnt = 3;
inline void MsgPlayerBagItem::clear_cnt() {
  cnt_ = PROTOBUF_LONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::int64 MsgPlayerBagItem::_internal_cnt() const {
  return cnt_;
}
inline ::PROTOBUF_NAMESPACE_ID::int64 MsgPlayerBagItem::cnt() const {
  // @@protoc_insertion_point(field_get:MsgPlayerBagItem.cnt)
  return _internal_cnt();
}
inline void MsgPlayerBagItem::_internal_set_cnt(::PROTOBUF_NAMESPACE_ID::int64 value) {
  
  cnt_ = value;
}
inline void MsgPlayerBagItem::set_cnt(::PROTOBUF_NAMESPACE_ID::int64 value) {
  _internal_set_cnt(value);
  // @@protoc_insertion_point(field_set:MsgPlayerBagItem.cnt)
}

// map<int32, int32> attr = 4;
inline int MsgPlayerBagItem::_internal_attr_size() const {
  return attr_.size();
}
inline int MsgPlayerBagItem::attr_size() const {
  return _internal_attr_size();
}
inline void MsgPlayerBagItem::clear_attr() {
  attr_.Clear();
}
inline const ::PROTOBUF_NAMESPACE_ID::Map< ::PROTOBUF_NAMESPACE_ID::int32, ::PROTOBUF_NAMESPACE_ID::int32 >&
MsgPlayerBagItem::_internal_attr() const {
  return attr_.GetMap();
}
inline const ::PROTOBUF_NAMESPACE_ID::Map< ::PROTOBUF_NAMESPACE_ID::int32, ::PROTOBUF_NAMESPACE_ID::int32 >&
MsgPlayerBagItem::attr() const {
  // @@protoc_insertion_point(field_map:MsgPlayerBagItem.attr)
  return _internal_attr();
}
inline ::PROTOBUF_NAMESPACE_ID::Map< ::PROTOBUF_NAMESPACE_ID::int32, ::PROTOBUF_NAMESPACE_ID::int32 >*
MsgPlayerBagItem::_internal_mutable_attr() {
  return attr_.MutableMap();
}
inline ::PROTOBUF_NAMESPACE_ID::Map< ::PROTOBUF_NAMESPACE_ID::int32, ::PROTOBUF_NAMESPACE_ID::int32 >*
MsgPlayerBagItem::mutable_attr() {
  // @@protoc_insertion_point(field_mutable_map:MsgPlayerBagItem.attr)
  return _internal_mutable_attr();
}

// map<int32, int32> dynaAttr = 5;
inline int MsgPlayerBagItem::_internal_dynaattr_size() const {
  return dynaattr_.size();
}
inline int MsgPlayerBagItem::dynaattr_size() const {
  return _internal_dynaattr_size();
}
inline void MsgPlayerBagItem::clear_dynaattr() {
  dynaattr_.Clear();
}
inline const ::PROTOBUF_NAMESPACE_ID::Map< ::PROTOBUF_NAMESPACE_ID::int32, ::PROTOBUF_NAMESPACE_ID::int32 >&
MsgPlayerBagItem::_internal_dynaattr() const {
  return dynaattr_.GetMap();
}
inline const ::PROTOBUF_NAMESPACE_ID::Map< ::PROTOBUF_NAMESPACE_ID::int32, ::PROTOBUF_NAMESPACE_ID::int32 >&
MsgPlayerBagItem::dynaattr() const {
  // @@protoc_insertion_point(field_map:MsgPlayerBagItem.dynaAttr)
  return _internal_dynaattr();
}
inline ::PROTOBUF_NAMESPACE_ID::Map< ::PROTOBUF_NAMESPACE_ID::int32, ::PROTOBUF_NAMESPACE_ID::int32 >*
MsgPlayerBagItem::_internal_mutable_dynaattr() {
  return dynaattr_.MutableMap();
}
inline ::PROTOBUF_NAMESPACE_ID::Map< ::PROTOBUF_NAMESPACE_ID::int32, ::PROTOBUF_NAMESPACE_ID::int32 >*
MsgPlayerBagItem::mutable_dynaattr() {
  // @@protoc_insertion_point(field_mutable_map:MsgPlayerBagItem.dynaAttr)
  return _internal_mutable_dynaattr();
}

// repeated int32 skills = 6;
inline int MsgPlayerBagItem::_internal_skills_size() const {
  return skills_.size();
}
inline int MsgPlayerBagItem::skills_size() const {
  return _internal_skills_size();
}
inline void MsgPlayerBagItem::clear_skills() {
  skills_.Clear();
}
inline ::PROTOBUF_NAMESPACE_ID::int32 MsgPlayerBagItem::_internal_skills(int index) const {
  return skills_.Get(index);
}
inline ::PROTOBUF_NAMESPACE_ID::int32 MsgPlayerBagItem::skills(int index) const {
  // @@protoc_insertion_point(field_get:MsgPlayerBagItem.skills)
  return _internal_skills(index);
}
inline void MsgPlayerBagItem::set_skills(int index, ::PROTOBUF_NAMESPACE_ID::int32 value) {
  skills_.Set(index, value);
  // @@protoc_insertion_point(field_set:MsgPlayerBagItem.skills)
}
inline void MsgPlayerBagItem::_internal_add_skills(::PROTOBUF_NAMESPACE_ID::int32 value) {
  skills_.Add(value);
}
inline void MsgPlayerBagItem::add_skills(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_add_skills(value);
  // @@protoc_insertion_point(field_add:MsgPlayerBagItem.skills)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int32 >&
MsgPlayerBagItem::_internal_skills() const {
  return skills_;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int32 >&
MsgPlayerBagItem::skills() const {
  // @@protoc_insertion_point(field_list:MsgPlayerBagItem.skills)
  return _internal_skills();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int32 >*
MsgPlayerBagItem::_internal_mutable_skills() {
  return &skills_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int32 >*
MsgPlayerBagItem::mutable_skills() {
  // @@protoc_insertion_point(field_mutable_list:MsgPlayerBagItem.skills)
  return _internal_mutable_skills();
}

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// MsgPlayerBag

// int32 cap = 1;
inline void MsgPlayerBag::clear_cap() {
  cap_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 MsgPlayerBag::_internal_cap() const {
  return cap_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 MsgPlayerBag::cap() const {
  // @@protoc_insertion_point(field_get:MsgPlayerBag.cap)
  return _internal_cap();
}
inline void MsgPlayerBag::_internal_set_cap(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  cap_ = value;
}
inline void MsgPlayerBag::set_cap(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_cap(value);
  // @@protoc_insertion_point(field_set:MsgPlayerBag.cap)
}

// map<int32, .MsgPlayerBagItem> msgPlayerBagItem = 2;
inline int MsgPlayerBag::_internal_msgplayerbagitem_size() const {
  return msgplayerbagitem_.size();
}
inline int MsgPlayerBag::msgplayerbagitem_size() const {
  return _internal_msgplayerbagitem_size();
}
inline void MsgPlayerBag::clear_msgplayerbagitem() {
  msgplayerbagitem_.Clear();
}
inline const ::PROTOBUF_NAMESPACE_ID::Map< ::PROTOBUF_NAMESPACE_ID::int32, ::MsgPlayerBagItem >&
MsgPlayerBag::_internal_msgplayerbagitem() const {
  return msgplayerbagitem_.GetMap();
}
inline const ::PROTOBUF_NAMESPACE_ID::Map< ::PROTOBUF_NAMESPACE_ID::int32, ::MsgPlayerBagItem >&
MsgPlayerBag::msgplayerbagitem() const {
  // @@protoc_insertion_point(field_map:MsgPlayerBag.msgPlayerBagItem)
  return _internal_msgplayerbagitem();
}
inline ::PROTOBUF_NAMESPACE_ID::Map< ::PROTOBUF_NAMESPACE_ID::int32, ::MsgPlayerBagItem >*
MsgPlayerBag::_internal_mutable_msgplayerbagitem() {
  return msgplayerbagitem_.MutableMap();
}
inline ::PROTOBUF_NAMESPACE_ID::Map< ::PROTOBUF_NAMESPACE_ID::int32, ::MsgPlayerBagItem >*
MsgPlayerBag::mutable_msgplayerbagitem() {
  // @@protoc_insertion_point(field_mutable_map:MsgPlayerBag.msgPlayerBagItem)
  return _internal_mutable_msgplayerbagitem();
}

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// MsgHero

// int32 uid = 1;
inline void MsgHero::clear_uid() {
  uid_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 MsgHero::_internal_uid() const {
  return uid_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 MsgHero::uid() const {
  // @@protoc_insertion_point(field_get:MsgHero.uid)
  return _internal_uid();
}
inline void MsgHero::_internal_set_uid(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  uid_ = value;
}
inline void MsgHero::set_uid(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_uid(value);
  // @@protoc_insertion_point(field_set:MsgHero.uid)
}

// int32 id = 2;
inline void MsgHero::clear_id() {
  id_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 MsgHero::_internal_id() const {
  return id_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 MsgHero::id() const {
  // @@protoc_insertion_point(field_get:MsgHero.id)
  return _internal_id();
}
inline void MsgHero::_internal_set_id(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  id_ = value;
}
inline void MsgHero::set_id(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_id(value);
  // @@protoc_insertion_point(field_set:MsgHero.id)
}

// int32 lv = 3;
inline void MsgHero::clear_lv() {
  lv_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 MsgHero::_internal_lv() const {
  return lv_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 MsgHero::lv() const {
  // @@protoc_insertion_point(field_get:MsgHero.lv)
  return _internal_lv();
}
inline void MsgHero::_internal_set_lv(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  lv_ = value;
}
inline void MsgHero::set_lv(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_lv(value);
  // @@protoc_insertion_point(field_set:MsgHero.lv)
}

// map<int32, .MsgPlayerBagItem> msgPlayerBagItem = 4;
inline int MsgHero::_internal_msgplayerbagitem_size() const {
  return msgplayerbagitem_.size();
}
inline int MsgHero::msgplayerbagitem_size() const {
  return _internal_msgplayerbagitem_size();
}
inline void MsgHero::clear_msgplayerbagitem() {
  msgplayerbagitem_.Clear();
}
inline const ::PROTOBUF_NAMESPACE_ID::Map< ::PROTOBUF_NAMESPACE_ID::int32, ::MsgPlayerBagItem >&
MsgHero::_internal_msgplayerbagitem() const {
  return msgplayerbagitem_.GetMap();
}
inline const ::PROTOBUF_NAMESPACE_ID::Map< ::PROTOBUF_NAMESPACE_ID::int32, ::MsgPlayerBagItem >&
MsgHero::msgplayerbagitem() const {
  // @@protoc_insertion_point(field_map:MsgHero.msgPlayerBagItem)
  return _internal_msgplayerbagitem();
}
inline ::PROTOBUF_NAMESPACE_ID::Map< ::PROTOBUF_NAMESPACE_ID::int32, ::MsgPlayerBagItem >*
MsgHero::_internal_mutable_msgplayerbagitem() {
  return msgplayerbagitem_.MutableMap();
}
inline ::PROTOBUF_NAMESPACE_ID::Map< ::PROTOBUF_NAMESPACE_ID::int32, ::MsgPlayerBagItem >*
MsgHero::mutable_msgplayerbagitem() {
  // @@protoc_insertion_point(field_mutable_map:MsgHero.msgPlayerBagItem)
  return _internal_mutable_msgplayerbagitem();
}

// map<int32, int32> attrs = 5;
inline int MsgHero::_internal_attrs_size() const {
  return attrs_.size();
}
inline int MsgHero::attrs_size() const {
  return _internal_attrs_size();
}
inline void MsgHero::clear_attrs() {
  attrs_.Clear();
}
inline const ::PROTOBUF_NAMESPACE_ID::Map< ::PROTOBUF_NAMESPACE_ID::int32, ::PROTOBUF_NAMESPACE_ID::int32 >&
MsgHero::_internal_attrs() const {
  return attrs_.GetMap();
}
inline const ::PROTOBUF_NAMESPACE_ID::Map< ::PROTOBUF_NAMESPACE_ID::int32, ::PROTOBUF_NAMESPACE_ID::int32 >&
MsgHero::attrs() const {
  // @@protoc_insertion_point(field_map:MsgHero.attrs)
  return _internal_attrs();
}
inline ::PROTOBUF_NAMESPACE_ID::Map< ::PROTOBUF_NAMESPACE_ID::int32, ::PROTOBUF_NAMESPACE_ID::int32 >*
MsgHero::_internal_mutable_attrs() {
  return attrs_.MutableMap();
}
inline ::PROTOBUF_NAMESPACE_ID::Map< ::PROTOBUF_NAMESPACE_ID::int32, ::PROTOBUF_NAMESPACE_ID::int32 >*
MsgHero::mutable_attrs() {
  // @@protoc_insertion_point(field_mutable_map:MsgHero.attrs)
  return _internal_mutable_attrs();
}

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// MsgPlayer

// int32 uid = 1;
inline void MsgPlayer::clear_uid() {
  uid_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 MsgPlayer::_internal_uid() const {
  return uid_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 MsgPlayer::uid() const {
  // @@protoc_insertion_point(field_get:MsgPlayer.uid)
  return _internal_uid();
}
inline void MsgPlayer::_internal_set_uid(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  uid_ = value;
}
inline void MsgPlayer::set_uid(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_uid(value);
  // @@protoc_insertion_point(field_set:MsgPlayer.uid)
}

// string name = 2;
inline void MsgPlayer::clear_name() {
  name_.ClearToEmpty();
}
inline const std::string& MsgPlayer::name() const {
  // @@protoc_insertion_point(field_get:MsgPlayer.name)
  return _internal_name();
}
inline void MsgPlayer::set_name(const std::string& value) {
  _internal_set_name(value);
  // @@protoc_insertion_point(field_set:MsgPlayer.name)
}
inline std::string* MsgPlayer::mutable_name() {
  // @@protoc_insertion_point(field_mutable:MsgPlayer.name)
  return _internal_mutable_name();
}
inline const std::string& MsgPlayer::_internal_name() const {
  return name_.Get();
}
inline void MsgPlayer::_internal_set_name(const std::string& value) {
  
  name_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void MsgPlayer::set_name(std::string&& value) {
  
  name_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:MsgPlayer.name)
}
inline void MsgPlayer::set_name(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  name_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:MsgPlayer.name)
}
inline void MsgPlayer::set_name(const char* value,
    size_t size) {
  
  name_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:MsgPlayer.name)
}
inline std::string* MsgPlayer::_internal_mutable_name() {
  
  return name_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* MsgPlayer::release_name() {
  // @@protoc_insertion_point(field_release:MsgPlayer.name)
  return name_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void MsgPlayer::set_allocated_name(std::string* name) {
  if (name != nullptr) {
    
  } else {
    
  }
  name_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), name,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:MsgPlayer.name)
}

// map<int32, .MsgPlayerBag> msgPlayerBag = 3;
inline int MsgPlayer::_internal_msgplayerbag_size() const {
  return msgplayerbag_.size();
}
inline int MsgPlayer::msgplayerbag_size() const {
  return _internal_msgplayerbag_size();
}
inline void MsgPlayer::clear_msgplayerbag() {
  msgplayerbag_.Clear();
}
inline const ::PROTOBUF_NAMESPACE_ID::Map< ::PROTOBUF_NAMESPACE_ID::int32, ::MsgPlayerBag >&
MsgPlayer::_internal_msgplayerbag() const {
  return msgplayerbag_.GetMap();
}
inline const ::PROTOBUF_NAMESPACE_ID::Map< ::PROTOBUF_NAMESPACE_ID::int32, ::MsgPlayerBag >&
MsgPlayer::msgplayerbag() const {
  // @@protoc_insertion_point(field_map:MsgPlayer.msgPlayerBag)
  return _internal_msgplayerbag();
}
inline ::PROTOBUF_NAMESPACE_ID::Map< ::PROTOBUF_NAMESPACE_ID::int32, ::MsgPlayerBag >*
MsgPlayer::_internal_mutable_msgplayerbag() {
  return msgplayerbag_.MutableMap();
}
inline ::PROTOBUF_NAMESPACE_ID::Map< ::PROTOBUF_NAMESPACE_ID::int32, ::MsgPlayerBag >*
MsgPlayer::mutable_msgplayerbag() {
  // @@protoc_insertion_point(field_mutable_map:MsgPlayer.msgPlayerBag)
  return _internal_mutable_msgplayerbag();
}

// map<int32, .MsgHero> msgHero = 4;
inline int MsgPlayer::_internal_msghero_size() const {
  return msghero_.size();
}
inline int MsgPlayer::msghero_size() const {
  return _internal_msghero_size();
}
inline void MsgPlayer::clear_msghero() {
  msghero_.Clear();
}
inline const ::PROTOBUF_NAMESPACE_ID::Map< ::PROTOBUF_NAMESPACE_ID::int32, ::MsgHero >&
MsgPlayer::_internal_msghero() const {
  return msghero_.GetMap();
}
inline const ::PROTOBUF_NAMESPACE_ID::Map< ::PROTOBUF_NAMESPACE_ID::int32, ::MsgHero >&
MsgPlayer::msghero() const {
  // @@protoc_insertion_point(field_map:MsgPlayer.msgHero)
  return _internal_msghero();
}
inline ::PROTOBUF_NAMESPACE_ID::Map< ::PROTOBUF_NAMESPACE_ID::int32, ::MsgHero >*
MsgPlayer::_internal_mutable_msghero() {
  return msghero_.MutableMap();
}
inline ::PROTOBUF_NAMESPACE_ID::Map< ::PROTOBUF_NAMESPACE_ID::int32, ::MsgHero >*
MsgPlayer::mutable_msghero() {
  // @@protoc_insertion_point(field_mutable_map:MsgPlayer.msgHero)
  return _internal_mutable_msghero();
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_PlayerDb_2eproto
